### ISSUE TITLE
[Feature Request] Implementing Sparklines

### ISSUE THREAD

**Issue by brandleesee** [pstadler/ticker.sh#13]
May I suggest to implement sparklines for a quick reference of the symbol's performance.

As a concept I envision something like this:

![1](https://user-images.githubusercontent.com/12674437/63090107-84f32580-bf5a-11e9-99d4-8b488b2ac8f8.png)

**Comment by pstadler** [comment]
How is this even possible?

**Comment by brandleesee** [comment]
In implementing that feature, script would have stopped being pure bash so your decision is understandable.

**Comment by pstadler** [comment]
Sorry if this came over a bit rude. How do you think this would work in a terminal? Using inline pictures?

**Comment by brandleesee** [comment]
**General Information**

- https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001OR
- https://github.com/jweir/sparkline

**Examples**

1. https://github.com/holman/spark ▁▂▃▅▇ 
2. https://github.com/deeplook/sparklines ▂▇▁█▂█▁█ 
3. https://github.com/mbauman/Sparklines.jl ▄▅▅▆▇▇▇███▇▇▆▆▅▅▄▃▂▂▁▁▁▁▁▁▁▁▂▂▃▄ 
4. https://github.com/omgnuts/gospark ▅▂▅▆▆▇▇▇█▆▇▄▅▆▅▅▁▁▂▃▂▁▂▃▄▄▆▅▂▃▆▅▄▂▅ 

Please note that some of the examples above may not be well suited or downright suitable for implementation in a terminal.

Referenced here, too: https://github.com/mop-tracker/mop/issues/16
