### ISSUE TITLE
Symbol with "-" are not supported

### ISSUE THREAD

**Issue by miguipda1** [pstadler/ticker.sh#17]
Hi,

because I have some symbols where the caracter "-" is included your script return those errors :
No results for symbol "AGS-BE"
No results for symbol "XFAB-FR"

It concern the stocks AGEAS and X-FAB.

Sincerely thank you to solve this problem because I suppose I am not alone in this case.

Have a nice day.

Miguipda

**Comment by pstadler** [comment]
Yahoo lists this stock as `AGS.BR` (Brussels) and `XFB.PA` (Paris).

**Comment by miguipda1** [comment]
Hi,

same problem with ".". The script returns : No results for symbol "XFAB.FR"

Sincerely thank you to solve it ;-)

With pleasure to get back your script that is really appreciated.

Have a nice day.

2020-02-17 8:10 UTC+01:00, Patrick Stadler <notifications@github.com>:
> Yahoo lists this stock as `AGS.BR` (Brussels) and `XFB.PA` (Paris).
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pstadler/ticker.sh/issues/17#issuecomment-586847953


-- 
_______________

 米革耳 - Mig ;-)
_______________

**Comment by miguipda1** [comment]
Sincerely thank you. It works perfectly with the right symbol you told me ;-)

Have a nice day.

2020-02-17 8:10 UTC+01:00, Patrick Stadler <notifications@github.com>:
> Yahoo lists this stock as `AGS.BR` (Brussels) and `XFB.PA` (Paris).
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pstadler/ticker.sh/issues/17#issuecomment-586847953


-- 
_______________

 米革耳 - Mig ;-)
_______________
