### ISSUE TITLE
Upgrade request - Display personal gains/ loose for each symbol

### ISSUE THREAD

**Issue by miguipda1** [pstadler/ticker.sh#18]
Hi,

could you please upgrade your script by considering this small parameter addon.

Your script can quickly help us to see how much we gain or loose with this tips.

Let me explain by this example :
   I bought 25 stocks of AAPL at the price of USD100.05
   Then if I mention it as parameter in your script (by considering you parse the symbols content) it could display in one shot which symbol allow us to gain or loose.
   Your script will then become something like this : 
           $ ./ticker.sh [25*100.05]AAPL MSFT GOOG BTC-USD
   
That could give as result :
   AAPL            325.05        0.10     (0.03%) *     [25*100.05]5625
   MSFT           185.30       -0.05    (-0.03%) *
   GOOG        1520.84        0.10     (0.01%) *
   BTC-USD    9585.88   -341.63    (-3.44%) 
   
As I just mentioned the AAPL amount of stock and price I bought between brackets "[25\*100.05]" only this line have to  display this gain or loose result.
Like you did previously for a great visibility this "[25*100.05]" should be print in grey and the result in green for gains or red for loose.

By hoping you could add this small functionality to your script it could sincerely be appreciated by everybody.

Have a nice day.

**Comment by pstadler** [comment]
Thanks for your request.

ticker.sh should remain simple. Check out this project instead: https://github.com/achannarasappa/ticker

**Comment by miguipda1** [comment]
Hi,

sincerely thank you.

Have a nice day and tale care.

Bye

2021-02-03 14:16 UTC+01:00, Patrick Stadler <notifications@github.com>:
> Closed #18.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pstadler/ticker.sh/issues/18#event-4285187730


-- 
_______________

 米革耳 - Mig ;-)
_______________
