### ISSUE TITLE
Other possible field items?

### ISSUE THREAD

**Issue by airbete** [pstadler/ticker.sh#2]
Thank you for sharing this code.

Are there any field items for Open, High, Low and Volume?

Do you know of a web site describing this api?

Thank you,

AB.

**Comment by pstadler** [comment]
I’m not aware of any documents describing this API, but you can call it without fields to get the full response, e.g https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&symbols=TSLA

**Comment by brandleesee** [comment]
This documentation seems relevant:
https://blog.api.rakuten.net/api-tutorial-yahoo-finance/
