### ISSUE TITLE
a couple of simple improvements

### ISSUE THREAD

**Issue by rr0ss0rr** [pstadler/ticker.sh#20]
For your consideration...

`#!/usr/bin/env bash`
for those of us who had to upgrade bash into a different directory (Mac users)

add `symbol=${symbol^^}`  uppercase prior to marketState query (so "aapl" & "AAPL"work the same)

Thanks

**Comment by rr0ss0rr** [comment]
Thanks. Can you also include “#!/usr/bin/env bash” ?

**Comment by pstadler** [comment]
I changed this on master.
