### ISSUE TITLE
problem with floating point conversion

### ISSUE THREAD

**Issue by yadaniel** [pstadler/ticker.sh#23]
floating point conversion with printf seems to blow up when there are trailing spaces in variables
I added 3 lines to the script and it works fine now.
Thank you for the script.

  else
    nonRegularMarketSign=''
    price=$(query $symbol 'regularMarketPrice')
    diff=$(query $symbol 'regularMarketChange')
    percent=$(query $symbol 'regularMarketChangePercent')
  fi

+  price=${price%%[[:space:]]}
+  diff=${diff%%[[:space:]]}
+  percent=${percent%%[[:space:]]}

**Comment by yadaniel** [comment]
carrige return seems to be attached to variables
somehow space seems to work in the script but not on command line

  price=${price%%'\r'}
  diff=${diff%%'\r'}
  percent=${percent%%'\r'}

**Comment by pstadler** [comment]
Which operating system / shell are you using?

**Comment by yadaniel** [comment]
I am using cygwin and my shell is bash
$ echo $BASH_VERSION
4.4.12(3)-release

Here is the output.

$ ./ticker.sh MSFT
: Ungültige Zahl.ile 81: printf: 213.98
MSFT          0.00


81 is the line with
    printf "%-10s$COLOR_BOLD%8.2f$COLOR_RESET" $symbol $price
213.98 comes from price

when I add debug option
set -x

+ color='\e[31m'
+ '[' $'213.98\r' '!=' null ']'
+ printf '%-10s\e[1;37m%8.2f\e[00m' MSFT $'213.98\r'
: Ungültige Zahl.ile 82: printf: 213.98
MSFT          0.00

So, '\r' probably gets fetched from request and gets even interpreted by printf.
Don't know why '$' appears in '[' $'213.98\r' '!=' null ']'

  price=${price%%[[:space:]]}
Somehow [[:space:]] works in script robust

  price=${price%%'\r'}
Somehow this does not work in script any more :)

I am just a bash user, possible that I have mixed something up.

**Comment by pstadler** [comment]
Please try to change `LC_NUMERIC` and `LANG` to `en_US.UTF-8` [here](https://github.com/pstadler/ticker.sh/blob/master/ticker.sh#L4-L5) and let me know whether this solves the problem.
