### ISSUE TITLE
Script stopped working

### ISSUE THREAD

**Issue by WeaponX1** [pstadler/ticker.sh#32]
# sh ticker2.sh AAPL
No results for symbol "AAPL"

could it be yahoo API changes were made?

**Comment by pstadler** [comment]
works for me.

**Comment by WeaponX1** [comment]
Hi Patrick,

Apologies for the late response, after your last comment I reinstalled my OS (Archlinux) and also installed your script on another Linux computer and won't work.

At this point, I am assuming that Yahoo most probably blacklisted my IP. I will spend more time troubleshooting it and if I find anything I will let you know.

thank you for your reply,


Shant Kassardjian

________________________________
