### ISSUE TITLE
stopped working jq: error (at <stdin>:1): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by markmark1** [pstadler/ticker.sh#34]
jq: error (at <stdin>:1): Cannot iterate over null (null)

 Advice:
    Nothing found for symbol ^N225
    Lookup the right one: finance.yahoo.com/lookup
=====================================================

**Comment by jmdugan** [comment]
yup yup searching for alternative sources too

**Comment by phish0r** [comment]
Anyone know how to fix this yet?

**Comment by pstadler** [comment]
Duplicate of #33
