### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by jman223** [pstadler/ticker.sh#43]
Running the script has failed for the past couple of days. 

crumb.txt says "Too Many Requests". 

I thought my IP may have been banned, so I tried via an Amazon AWS server and received the same result.

**Comment by jman223** [comment]
Adding the following to curl resolves the issue:

-A "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0"

**Comment by jman223** [comment]
Adding the following to curl resolves the issue:

-A "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0"

**Comment by phish0r** [comment]
I'm also running into Too Many Requests.  No errors from the script itself, just no output.  When I check my crumb.txt file, I have the Too Many Requests error message.  I attempted to do the workaround you suggested, but it didn't work for me.

**Comment by jman223** [comment]
I didn't test this extensively, so not sure if both are required, but I added to both curl commands in the preflight function.

```
AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0"

preflight () {
  # rather than "finance", use the "fc" subdomain which doesn't redirect to a consent page
  curl --silent -A "$AGENT" --output /dev/null --cookie-jar "$COOKIE_FILE" "https://fc.yahoo.com" \
  -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
  curl --silent -A "$AGENT" -b "$COOKIE_FILE" "https://query1.finance.yahoo.com/v1/test/getcrumb" \
    > "$CRUMB_FILE"
}
```

**Comment by phish0r** [comment]
Well, that didn't work but what did we switching connections over to my mobile hotspot, then connecting back to my Wifi.  Not sure why that worked, but it did.

**Comment by pstadler** [comment]
-> #45
