### ISSUE TITLE
Too Many Requests in crumb.txt, no output from script

### ISSUE THREAD

**Issue by phish0r** [pstadler/ticker.sh#44]
I'm running into the Too Many Requests error. No errors from the script itself, just no output. When I check my crumb.txt file, I have the Too Many Requests error message.

**Comment by dropbrick** [comment]
Why is this closed ?

**Comment by phish0r** [comment]
I closed it because it doesn't seem to have been an issue with the script, I refreshed my internet connection and fixed it.  I think in my case I was IP banned.  I've since reduced the frequency of the time I'm polling the API now and hope that will resolve it.

**Comment by andymiller-og** [comment]
I have the same @phish0r ... I only poll on-demand, maybe 10-50 times per day randomly, depending... I think there have been some changes.

**Comment by appatalks** [comment]
+1 was effected. Looks like I got blocked by yahoo with 403 at some level

**Comment by pstadler** [comment]
#45
