### ISSUE TITLE
Invalid number

### ISSUE THREAD

**Issue by kallekutta** [pstadler/ticker.sh#6]
Hello,

I get this when I try your script:

`nils@HAL9000:/tmp$ ./ticker.sh AAPL
AAPL        220,00./ticker.sh: line 73: printf: -0.5380001: invalid number
./ticker.sh: line 73: printf: -1.1900024: invalid number
      0,00     (0,00%)`

Do you know what's wrong?

**Comment by pstadler** [comment]
it works fine if you only query for AAPL once.

**Comment by kallekutta** [comment]
Seems like the formatting of github code went wrong. I'm only querying AAPL once, here is the full debug output.

`nils@HAL9000:/tmp$ bash -x ./ticker.sh AAPL
+ set -e
+ LANG=en_US.UTF-8
+ SYMBOLS=("$@")
++ type jq
+ '[' -z AAPL ']'
+ FIELDS=(symbol marketState regularMarketPrice regularMarketChange regularMarketChangePercent preMarketPrice preMarketChange preMarketChangePercent postMarketPrice postMarketChange postMarketChangePercent)
+ API_ENDPOINT='https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com'
+ : '\e[1;37m'
+ : '\e[32m'
+ : '\e[31m'
+ : '\e[00m'
++ IFS=,
++ echo AAPL
+ symbols=AAPL
++ IFS=,
++ echo symbol,marketState,regularMarketPrice,regularMarketChange,regularMarketChangePercent,preMarketPrice,preMarketChange,preMarketChangePercent,postMarketPrice,postMarketChange,postMarketChangePercent
+ fields=symbol,marketState,regularMarketPrice,regularMarketChange,regularMarketChangePercent,preMarketPrice,preMarketChange,preMarketChangePercent,postMarketPrice,postMarketChange,postMarketChangePercent
++ curl --silent 'https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&fields=symbol,marketState,regularMarketPrice,regularMarketChange,regularMarketChangePercent,preMarketPrice,preMarketChange,preMarketChangePercent,postMarketPrice,postMarketChange,postMarketChangePercent&symbols=AAPL'
++ jq '.quoteResponse .result'
+ results='[
  {
    "language": "en-US",
    "region": "US",
    "quoteType": "EQUITY",
    "quoteSourceName": "Nasdaq Real Time Price",
    "exchange": "NMS",
    "market": "us_market",
    "preMarketChange": 3.1399994,
    "preMarketChangePercent": 1.4535688,
    "exchangeTimezoneName": "America/New_York",
    "regularMarketPreviousClose": 216.02,
    "preMarketPrice": 219.16,
    "preMarketTime": 1539955799,
    "gmtOffSetMilliseconds": -14400000,
    "sourceInterval": 15,
    "exchangeTimezoneShortName": "EDT",
    "marketState": "REGULAR",
    "tradeable": true,
    "regularMarketChangePercent": 1.7695096,
    "esgPopulated": false,
    "regularMarketPrice": 219.8425,
    "regularMarketTime": 1539957436,
    "regularMarketChange": 3.8224945,
    "exchangeDataDelayedBy": 0,
    "fullExchangeName": "NasdaqGS",
    "symbol": "AAPL"
  }
]'
++ IFS=' '
++ echo AAPL
+ for symbol in '$(IFS='\'' '\''; echo "${SYMBOLS[*]}")'
++ query AAPL marketState
++ jq -r '.[] | select (.symbol == "AAPL") | .marketState'
++ echo '[' '{' '"language":' '"en-US",' '"region":' '"US",' '"quoteType":' '"EQUITY",' '"quoteSourceName":' '"Nasdaq' Real Time 'Price",' '"exchange":' '"NMS",' '"market":' '"us_market",' '"preMarketChange":' 3.1399994, '"preMarketChangePercent":' 1.4535688, '"exchangeTimezoneName":' '"America/New_York",' '"regularMarketPreviousClose":' 216.02, '"preMarketPrice":' 219.16, '"preMarketTime":' 1539955799, '"gmtOffSetMilliseconds":' -14400000, '"sourceInterval":' 15, '"exchangeTimezoneShortName":' '"EDT",' '"marketState":' '"REGULAR",' '"tradeable":' true, '"regularMarketChangePercent":' 1.7695096, '"esgPopulated":' false, '"regularMarketPrice":' 219.8425, '"regularMarketTime":' 1539957436, '"regularMarketChange":' 3.8224945, '"exchangeDataDelayedBy":' 0, '"fullExchangeName":' '"NasdaqGS",' '"symbol":' '"AAPL"' '}' ']'
+ '[' -z REGULAR ']'
++ query AAPL marketState
++ jq -r '.[] | select (.symbol == "AAPL") | .marketState'
++ echo '[' '{' '"language":' '"en-US",' '"region":' '"US",' '"quoteType":' '"EQUITY",' '"quoteSourceName":' '"Nasdaq' Real Time 'Price",' '"exchange":' '"NMS",' '"market":' '"us_market",' '"preMarketChange":' 3.1399994, '"preMarketChangePercent":' 1.4535688, '"exchangeTimezoneName":' '"America/New_York",' '"regularMarketPreviousClose":' 216.02, '"preMarketPrice":' 219.16, '"preMarketTime":' 1539955799, '"gmtOffSetMilliseconds":' -14400000, '"sourceInterval":' 15, '"exchangeTimezoneShortName":' '"EDT",' '"marketState":' '"REGULAR",' '"tradeable":' true, '"regularMarketChangePercent":' 1.7695096, '"esgPopulated":' false, '"regularMarketPrice":' 219.8425, '"regularMarketTime":' 1539957436, '"regularMarketChange":' 3.8224945, '"exchangeDataDelayedBy":' 0, '"fullExchangeName":' '"NasdaqGS",' '"symbol":' '"AAPL"' '}' ']'
+ '[' REGULAR == PRE ']'
++ query AAPL marketState
++ echo '[' '{' '"language":' '"en-US",' '"region":' '"US",' '"quoteType":' '"EQUITY",' '"quoteSourceName":' '"Nasdaq' Real Time 'Price",' '"exchange":' '"NMS",' '"market":' '"us_market",' '"preMarketChange":' 3.1399994, '"preMarketChangePercent":' 1.4535688, '"exchangeTimezoneName":' '"America/New_York",' '"regularMarketPreviousClose":' 216.02, '"preMarketPrice":' 219.16, '"preMarketTime":' 1539955799, '"gmtOffSetMilliseconds":' -14400000, '"sourceInterval":' 15, '"exchangeTimezoneShortName":' '"EDT",' '"marketState":' '"REGULAR",' '"tradeable":' true, '"regularMarketChangePercent":' 1.7695096, '"esgPopulated":' false, '"regularMarketPrice":' 219.8425, '"regularMarketTime":' 1539957436, '"regularMarketChange":' 3.8224945, '"exchangeDataDelayedBy":' 0, '"fullExchangeName":' '"NasdaqGS",' '"symbol":' '"AAPL"' '}' ']'
++ jq -r '.[] | select (.symbol == "AAPL") | .marketState'
+ '[' REGULAR '!=' REGULAR ']'
+ nonRegularMarketSign=
++ query AAPL regularMarketPrice
++ jq -r '.[] | select (.symbol == "AAPL") | .regularMarketPrice'
++ echo '[' '{' '"language":' '"en-US",' '"region":' '"US",' '"quoteType":' '"EQUITY",' '"quoteSourceName":' '"Nasdaq' Real Time 'Price",' '"exchange":' '"NMS",' '"market":' '"us_market",' '"preMarketChange":' 3.1399994, '"preMarketChangePercent":' 1.4535688, '"exchangeTimezoneName":' '"America/New_York",' '"regularMarketPreviousClose":' 216.02, '"preMarketPrice":' 219.16, '"preMarketTime":' 1539955799, '"gmtOffSetMilliseconds":' -14400000, '"sourceInterval":' 15, '"exchangeTimezoneShortName":' '"EDT",' '"marketState":' '"REGULAR",' '"tradeable":' true, '"regularMarketChangePercent":' 1.7695096, '"esgPopulated":' false, '"regularMarketPrice":' 219.8425, '"regularMarketTime":' 1539957436, '"regularMarketChange":' 3.8224945, '"exchangeDataDelayedBy":' 0, '"fullExchangeName":' '"NasdaqGS",' '"symbol":' '"AAPL"' '}' ']'
+ price=219.8425
++ query AAPL regularMarketChange
++ jq -r '.[] | select (.symbol == "AAPL") | .regularMarketChange'
++ echo '[' '{' '"language":' '"en-US",' '"region":' '"US",' '"quoteType":' '"EQUITY",' '"quoteSourceName":' '"Nasdaq' Real Time 'Price",' '"exchange":' '"NMS",' '"market":' '"us_market",' '"preMarketChange":' 3.1399994, '"preMarketChangePercent":' 1.4535688, '"exchangeTimezoneName":' '"America/New_York",' '"regularMarketPreviousClose":' 216.02, '"preMarketPrice":' 219.16, '"preMarketTime":' 1539955799, '"gmtOffSetMilliseconds":' -14400000, '"sourceInterval":' 15, '"exchangeTimezoneShortName":' '"EDT",' '"marketState":' '"REGULAR",' '"tradeable":' true, '"regularMarketChangePercent":' 1.7695096, '"esgPopulated":' false, '"regularMarketPrice":' 219.8425, '"regularMarketTime":' 1539957436, '"regularMarketChange":' 3.8224945, '"exchangeDataDelayedBy":' 0, '"fullExchangeName":' '"NasdaqGS",' '"symbol":' '"AAPL"' '}' ']'
+ diff=3.8224945
++ query AAPL regularMarketChangePercent
++ echo '[' '{' '"language":' '"en-US",' '"region":' '"US",' '"quoteType":' '"EQUITY",' '"quoteSourceName":' '"Nasdaq' Real Time 'Price",' '"exchange":' '"NMS",' '"market":' '"us_market",' '"preMarketChange":' 3.1399994, '"preMarketChangePercent":' 1.4535688, '"exchangeTimezoneName":' '"America/New_York",' '"regularMarketPreviousClose":' 216.02, '"preMarketPrice":' 219.16, '"preMarketTime":' 1539955799, '"gmtOffSetMilliseconds":' -14400000, '"sourceInterval":' 15, '"exchangeTimezoneShortName":' '"EDT",' '"marketState":' '"REGULAR",' '"tradeable":' true, '"regularMarketChangePercent":' 1.7695096, '"esgPopulated":' false, '"regularMarketPrice":' 219.8425, '"regularMarketTime":' 1539957436, '"regularMarketChange":' 3.8224945, '"exchangeDataDelayedBy":' 0, '"fullExchangeName":' '"NasdaqGS",' '"symbol":' '"AAPL"' '}' ']'
++ jq -r '.[] | select (.symbol == "AAPL") | .regularMarketChangePercent'
+ percent=1.7695096
+ '[' 3.8224945 == 0 ']'
+ echo 3.8224945
+ grep -q '^-'
+ color='\e[32m'
+ printf '%-10s\e[1;37m%8.2f\e[00m' AAPL 219.8425
./ticker.sh: line 72: printf: 219.8425: invalid number
AAPL          0,00`

**Comment by pstadler** [comment]
can you try with `LC_NUMERIC=en_US.UTF-8`?

**Comment by kallekutta** [comment]
It works, thank you!
