### ISSUE TITLE
this is super cool -> instead of going blank can it refresh in place

### ISSUE THREAD

**Issue by victusfate** [pstadler/ticker.sh#7]
I was looking at bash printf with \r but no luck yet, the do clear seems to make it blinky/distracting more than I'd prefer. If not that's cool too, thanks for putting it together.

**Comment by pstadler** [comment]
I recommend using `watch` in this case. Example:

```sh
watch -n 5 -t -c ./ticker.sh AAPL MSFT GOOG BTC-USD
```

**Comment by pstadler** [comment]
Added this to the readme.
